### ISSUE TITLE
Make command not found

### ISSUE THREAD

**Issue by christophe-mailfert** [jakzal/phpqa#116]
Hey,

Thx a lot for your work.
I'm trying to run command from a make file but make seems not installed.

```
php -v
PHP 7.3.2 (cli) (built: Feb  9 2019 01:32:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
$ make test
/bin/bash: line 76: make: command not found
```

Could we install make on every build ?

My Makefile
```
test:
	php-cs-fixer fix --dry-run --using-cache=no --verbose --diff
```

My gitlab ci:
```
php-cs-fixer:
  image: jakzal/phpqa
  stage: test
  script:
    - php -v
    - make test
  allow_failure: true
```

Thx for advance.
