### ISSUE TITLE
phpstan-symfoy not works

### ISSUE THREAD

**Issue by tydoo** [jakzal/phpqa#406]
Hello,

I use jakzal/phpqa:php8.2 on CI Gitlab and symfony ext for PHPstan not works.

I have this error : 

```
$ phpstan analyse --memory-limit 1G
Note: Using configuration file /builds/si/si-sdlp-v2-symfony/phpstan.neon.
Invalid configuration:
Unexpected item 'parameters › symfony'.
```

phpstan.neon
```
parameters:
    level: 6

    symfony:
        containerXmlPath: var/cache/dev/App_KernelDevDebugContainer.xml
    scanDirectories:
        - var/cache/dev/Symfony/Config

    checkGenericClassInNonGenericObjectType: false
    checkMissingIterableValueType: false

    paths:
        - src

```

.gitlab-ci.yml
```
image: jakzal/phpqa:php8.2

cache:
  paths:
    - vendor/

before_script:
  - composer install

stages:
  - Code_Quality

php_stan:
  stage: Code_Quality
  script:
    - phpstan analyse --memory-limit 1G
```

Thanks for your help
